services:
  punto-fusion-api:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git openssl && rm -rf /temp_code && git clone https://${GIT_TOKEN}@github.com/aromeroconde/puntofusion.git /temp_code && rm -rf /app/public /app/src /app/prisma && cp -a /temp_code/punto_fusion_api/* /app/ && rm -rf /temp_code && npm install && npx prisma generate && npm run build && node dist/index.js"
    environment:
      - NODE_ENV=production
      - PORT=3100
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - AGENDADOR_API_URL=${AGENDADOR_API_URL}
      - ALEGRA_USER=${ALEGRA_USER}
      - ALEGRA_TOKEN=${ALEGRA_TOKEN}
      - GIT_TOKEN=${GIT_TOKEN}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.puntofusion-api.rule=Host(`puntofusion.smartnexo.com`) && PathPrefix(`/api`)"
        - "traefik.http.services.puntofusion-api.loadbalancer.server.port=3100"
        - "traefik.http.routers.puntofusion-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.puntofusion-api.entrypoints=websecure"
        - "traefik.http.routers.puntofusion-api.tls=true"
    networks:
      - general_network

  punto-fusion-web:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git nginx && rm -rf /temp_code && git clone https://${GIT_TOKEN}@github.com/aromeroconde/puntofusion.git /temp_code && rm -rf /app/* && cp -a /temp_code/punto_fusion_web/dist /app/public && rm -rf /temp_code && cp /etc/nginx/nginx.conf /app/nginx.conf && sed -i 's|worker_processes 1;|worker_processes auto;|g' /app/nginx.conf && nginx -g 'daemon off;'"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.puntofusion-web.rule=Host(`puntofusion.smartnexo.com`)"
        - "traefik.http.services.puntofusion-web.loadbalancer.server.port=80"
        - "traefik.http.routers.puntofusion-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.puntofusion-web.entrypoints=websecure"
        - "traefik.http.routers.puntofusion-web.tls=true"
    networks:
      - general_network

networks:
  general_network:
    external: true
